from enum import Enum


class Categorie(Enum):
    R0 = "R0"
    R1 = "R1"
    R2  = "R2"
    R3 = "R3"
    R4= "R4"
    R5  = "R5"
    R6 = "R6"
    R7 = "R7"
    R8  = "R8"
    R9 = "R9"
    R10 = "R10"
class Niveau(Enum):
    rez_de_chaussee_gauche = "rez-de-chaussee à gauche"
    rez_de_chaussee_droit = "rez-de-chaussee à droit"
    etage_1_gauche = "premier etage à gauche"
    etage_1_droit = "premier etage à droit"
    etage_2_gauche = "deuxieme etage à gauche"
    etage_2_droit = "deuxieme etage à droit"
    etage_3_gauche = "troixieme etage à gauche"
    etage_3_droit = "troixieme etage à droit"
    etage_4_gauche = "quatrieme etage à gauche"
    etage_4_droit = "quatrieme etage à droit"
    etage_5_gauche = "cinquieme etage à gauche"
    etage_5_droit = "cinquieme etage à droit"
    etage_6_gauche = "sixieme etage à gauche"
    etage_6_droit = "sixieme etage à droit"
    etage_7_gauche = "septieme etage à gauche"
    etage_7_droit = "septieme etage àdroit"
    etage_8_gauche = "huitieme etage à gauche"
    etage_8_droit = "huitieme etage à droit"
    etage_9_gauche = "nuevieme etage à gauche"
    etage_9_droit = "neuvieme etage à droit"
    etage_10_gauche = "dixieme etage à gauche"
    etage_10_droit = "dixieme etage à droit"


class TypeAppartement(Enum):
    studio = "studio"
    F2  = "F2"
    F3 = "F3"
    F4= "F4"
    F5  = "F5"
    F6 = "F6"
    F7 = "F7"
    F8  = "F8"
    F9 = "F9"
    F10 = "F10"
class EtatBien(Enum):
    neuf = "neuf"
    tresBonEtat  = "tresBonEtat"
    bonEtat = "bonEtat"
    mauvaisEtat= "mauvaisEtat"
